
Array Oprations

In [7]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing ",arr[2:7])
print("with steps",arr[1:8:2])
print("Negative slicing",arr[-5:-2])

Basic slicing  [3 4 5 6 7]
with steps [2 4 6 8]
Negative slicing [6 7 8]


In [ ]:
arr2=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print("Specific element",arr2[0,1])
print("Entire row",arr2[1])
print("Only column",arr2[:,0])

Specific element 2
Entire row [4 5 6]
Only column [1 4 7]


## sorting

In [8]:
arr=np.array([1,2,32,1,42,1,3,5,64,3,1])
print("sort",np.sort(arr))

arr2=np.array([[1,5],
             [5,6],
             [3,4]])
print("sort 2d arry by column",np.sort(arr2,axis=0))

sort [ 1  1  1  1  2  3  3  5 32 42 64]
sort 2d arry by column [[1 4]
 [3 5]
 [5 6]]



## Filters

In [ ]:
numbers=np.array([1,2,3,4,5,6,7,8,9])
even_numbers=numbers[numbers%2==0]
print("Even numbers",even_numbers)



Even numbers [2 4 6 8]


In [ ]:
mask=numbers>5
print("Greater than 5",numbers[mask])

Greater than 5 [6 7 8 9]


## indexs and where()

In [ ]:
indices=[0,2,4]
print(numbers[indices])

where_result=np.where(numbers>5)
print(where_result)
print("NP where result",numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8]),)
NP where result [6 7 8 9]


In [ ]:
condition_arr=np.where(numbers>5,numbers*2,numbers)
print("Condition array",condition_arr)

Condition array [ 1  2  3  4  5 12 14 16 18]


## Adding and Removing

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

combined=np.concatenate((arr1,arr2))
print("Combined array",combined)

Combined array [1 2 3 4 5 6]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6,7])
c=np.array([7,8,9])

print("Compatibility check",a.shape==b.shape)

Compatibility check False


In [ ]:
original=np.array([1,2,3])
new_row=np.array([4,5,6])

new_arr=np.vstack((original,new_row))
print(original)
print("New array after vstack",new_arr)

new_column=np.array([[7],[8]])
arr=np.hstack((new_arr,new_column))
print("New column array",arr)

[1 2 3]
New array after vstack [[1 2 3]
 [4 5 6]]
New column array [[1 2 3 7]
 [4 5 6 8]]
