### NUMPY

In [1]:
import numpy as np

In [ ]:
arr1=np.array([1, 2, 3])
print(arr1)
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [ ]:
list=[1, 2, 3]
print("This is list:", list*2)

pyarr=np.array([2,4,6])
print("This is numpy array:", pyarr)

This is list: [1, 2, 3, 1, 2, 3]
This is numpy array: [2 4 6]


In [ ]:
import time
start=time.time()
list1=[i*2 for i in range(1000000)]
print("\n list opreation time:",time.time()-start)

arraypy=np.array([i*2 for i in range(1000000)])
print("\n numpy array operation time:",time.time()-start)


 list opreation time: 0.04356980323791504

 numpy array operation time: 0.11705636978149414


###Crearting arrya

In [ ]:
zeros=np.zeros((2,3))
print(zeros)

ones=np.ones((3,4))
print(ones)

full=np.full((2,2),7)
print(full)

ramdom=np.random.random((2,3))
print(ramdom)

sequence=np.arange(0,10,2)
print(sequence)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7]
 [7 7]]
[[0.88206932 0.4407554  0.83908925]
 [0.90574581 0.21406634 0.84614395]]
[0 2 4 6 8]



###Matrix,Vector,Tensor

In [ ]:
vector=np.array([1,2,3])
print("Vector:\n",vector)

matrix=np.array([[1,2,3],
                 [4,5,6]])
print("Matrix:\n",matrix)

tensor=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print("Tensor:",tensor)


Vector:
 [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


###Array properties


In [ ]:
arr=np.array([1,2,3,4,5])
print("Shape:",arr.shape)
print("size:",arr.size )
print("dtype:",arr.dtype)   
print("Dimensions:",arr.ndim)

Shape: (5,)
size: 5
dtype: int64
Dimensions: 1


### Array reshape

In [ ]:
arr=np.arange(12)
print(arr)

reshape=arr.reshape(4,3)
print("Array reshaped:\n",reshape)

flattened=reshape.flatten()
print("Flattened :",flattened)

reveled=reshape.ravel()
print("Reveled:",reveled)

transposed=reshape.T
print("Transposed:\n",transposed)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
Array reshaped:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Flattened : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reveled: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed:
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
