## Student Data

In [1]:
import numpy as np

### Genrating student data

In [6]:
arr=np.random.randint(0, 101, (500, 5))
print(arr)

[[ 13  38  89  11  99]
 [100  44  61  84  76]
 [ 98  57  35  17  96]
 ...
 [  9   9  65  59   2]
 [ 11  42  91  63  25]
 [ 24  89  72  19  35]]


### Calculating the total marks of each student

In [10]:
total_marks = np.sum(arr, axis=1)
print("Total Marks:", total_marks)

Total Marks: [250 365 303 214 199 297 117 354 281 244 232 188 244 201 219 307 275 314
 107 356 284 227 228 197 253 284 200 216 286 262 190 314 252 236 278 338
 278 294 270 102 212 270 267 276 178 227 167 160 374 344 258 329 270 184
 198 340 204 212 100 331 213 309 300 135 324 298 270 273 300 102 137 283
 234 335 235 220 154 301 353 244 226 161 392 254 181 252 265 301 203 211
 211 131 289 180 273 197 223 228 279 127 280 217 360 299 280 357 260 435
 333 188 444 246 342 243 240 233 254 124 250 219 208 224 160 189 272 186
 233 213 287 213 256 308 173 201 152 213 278 240 316 289 287 264 255 274
 276 216 196 292 282 338 202 258 230 264 175 139 292 365 325 357 244 154
 191 295 294 179 245 224 175 203 272 207 267 410 229 233 148 256 202 261
 380 240 243 223 263 193 289 341 327 228 213 248 245 200 160 313 183 144
  70 155 166 153 345 267 368 347 256 231 179 306 225 162 217 225 130 142
 164 260 233 247 143 257 201 217 368 263 306 311 330 181 352 148 255 259
 211 344 324 309 287 249 349 217 239 1

In [ ]:
#Student percentage calculation
percentage=(total_marks/500)*100
for i, p in enumerate(percentage[:500], start=1):
    print(f"Student {i}: {p:.2f}%")

Student 1: 50.00%
Student 2: 73.00%
Student 3: 60.60%
Student 4: 42.80%
Student 5: 39.80%
Student 6: 59.40%
Student 7: 23.40%
Student 8: 70.80%
Student 9: 56.20%
Student 10: 48.80%
Student 11: 46.40%
Student 12: 37.60%
Student 13: 48.80%
Student 14: 40.20%
Student 15: 43.80%
Student 16: 61.40%
Student 17: 55.00%
Student 18: 62.80%
Student 19: 21.40%
Student 20: 71.20%
Student 21: 56.80%
Student 22: 45.40%
Student 23: 45.60%
Student 24: 39.40%
Student 25: 50.60%
Student 26: 56.80%
Student 27: 40.00%
Student 28: 43.20%
Student 29: 57.20%
Student 30: 52.40%
Student 31: 38.00%
Student 32: 62.80%
Student 33: 50.40%
Student 34: 47.20%
Student 35: 55.60%
Student 36: 67.60%
Student 37: 55.60%
Student 38: 58.80%
Student 39: 54.00%
Student 40: 20.40%
Student 41: 42.40%
Student 42: 54.00%
Student 43: 53.40%
Student 44: 55.20%
Student 45: 35.60%
Student 46: 45.40%
Student 47: 33.40%
Student 48: 32.00%
Student 49: 74.80%
Student 50: 68.80%
Student 51: 51.60%
Student 52: 65.80%
Student 53: 54.00%
St

In [ ]:
#Student Grading System
conditions = [
    percentage >= 90,
    percentage >= 85,
    percentage >= 80,
    percentage >= 75,
    percentage >= 70,
    percentage >= 65,
    percentage >= 60,
    percentage >= 50
]

grades = ['A+','A','B+','B','C+','C','D+','D']

Grade = np.select(conditions, grades, default='F')

print(Grade)

['D' 'C+' 'D+' 'F' 'F' 'D' 'F' 'C+' 'D' 'F' 'F' 'F' 'F' 'F' 'F' 'D+' 'D'
 'D+' 'F' 'C+' 'D' 'F' 'F' 'F' 'D' 'D' 'F' 'F' 'D' 'D' 'F' 'D+' 'D' 'F'
 'D' 'C' 'D' 'D' 'D' 'F' 'F' 'D' 'D' 'D' 'F' 'F' 'F' 'F' 'C+' 'C' 'D' 'C'
 'D' 'F' 'F' 'C' 'F' 'F' 'F' 'C' 'F' 'D+' 'D+' 'F' 'D+' 'D' 'D' 'D' 'D+'
 'F' 'F' 'D' 'F' 'C' 'F' 'F' 'F' 'D+' 'C+' 'F' 'F' 'F' 'B' 'D' 'F' 'D' 'D'
 'D+' 'F' 'F' 'F' 'F' 'D' 'F' 'D' 'F' 'F' 'F' 'D' 'F' 'D' 'F' 'C+' 'D' 'D'
 'C+' 'D' 'A' 'C' 'F' 'A' 'F' 'C' 'F' 'F' 'F' 'D' 'F' 'D' 'F' 'F' 'F' 'F'
 'F' 'D' 'F' 'F' 'F' 'D' 'F' 'D' 'D+' 'F' 'F' 'F' 'F' 'D' 'F' 'D+' 'D' 'D'
 'D' 'D' 'D' 'D' 'F' 'F' 'D' 'D' 'C' 'F' 'D' 'F' 'D' 'F' 'F' 'D' 'C+' 'C'
 'C+' 'F' 'F' 'F' 'D' 'D' 'F' 'F' 'F' 'F' 'F' 'D' 'F' 'D' 'B+' 'F' 'F' 'F'
 'D' 'F' 'D' 'B' 'F' 'F' 'F' 'D' 'F' 'D' 'C' 'C' 'F' 'F' 'F' 'F' 'F' 'F'
 'D+' 'F' 'F' 'F' 'F' 'F' 'F' 'C' 'D' 'C+' 'C' 'D' 'F' 'F' 'D+' 'F' 'F'
 'F' 'F' 'F' 'F' 'F' 'D' 'F' 'F' 'F' 'D' 'F' 'F' 'C+' 'D' 'D+' 'D+' 'C'
 'F' 'C+' 'F' 'D' 'D' 'F' 'C' 'D+' 'D+' 'D'

In [25]:
#Falied students
failed_students = np.where(Grade == 'F')[0] + 1
print("Failed Student Numbers:", failed_students)
print("Total Failed Students:", len(failed_students))

Failed Student Numbers: [  4   5   7  10  11  12  13  14  15  19  22  23  24  27  28  31  34  40
  41  45  46  47  48  54  55  57  58  59  61  64  70  71  73  75  76  77
  80  81  82  85  89  90  91  92  94  96  97  98 100 102 110 112 114 115
 116 118 120 121 122 123 124 126 127 128 130 133 134 135 136 138 146 147
 151 153 155 156 161 162 163 166 167 168 169 170 172 175 176 177 179 182
 183 184 186 190 191 192 193 194 195 197 198 199 200 201 202 208 209 211
 212 213 214 215 216 217 219 220 221 223 224 230 232 235 240 242 243 244
 245 247 248 249 250 252 255 256 257 259 260 264 266 267 269 271 273 274
 275 276 277 278 279 280 281 282 283 288 291 292 293 294 296 301 302 304
 305 307 308 312 319 320 323 325 326 328 329 330 331 336 337 338 339 342
 343 344 346 350 351 352 356 358 359 360 362 363 364 367 368 370 371 372
 376 378 379 380 381 385 386 389 391 392 395 399 402 409 411 412 414 417
 418 420 421 422 423 425 426 427 429 432 434 439 441 443 444 445 446 447
 449 450 451 454 456 457 46

In [28]:
#Topper student
topper_student= np.argmax(total_marks)
print(f"Topper Student Number: {topper_student + 1}")
print("Topper student marks:", total_marks[topper_student])
print("Topper student percentage:",percentage[topper_student])


Topper Student Number: 111
Topper student marks: 444
Topper student percentage: 88.8


In [29]:
#Subject-wise toppers
subject_toppers = np.argmax(arr, axis=0)

print("Subject Toppers:")
for i in range(5):
    print(f"Subject {i+1}: Student {subject_toppers[i]+1}")

Subject Toppers:
Subject 1: Student 2
Subject 2: Student 160
Subject 3: Student 129
Subject 4: Student 80
Subject 5: Student 11


In [30]:
#class statics
print("Highest Marks:", np.max(total_marks))
print("Lowest Marks:", np.min(total_marks))
print("Average Marks:", np.mean(total_marks))
print("Median Marks:", np.median(total_marks))
print("Standard Deviation:", np.std(total_marks))

Highest Marks: 444
Lowest Marks: 37
Average Marks: 244.092
Median Marks: 244.0
Standard Deviation: 67.01879986988726


In [32]:
#Number of students in each grade
unique, counts = np.unique(Grade, return_counts=True)

for grade, count in zip(unique, counts):
    print(f"{grade}: {count}")

A: 3
B: 5
B+: 2
C: 30
C+: 19
D: 137
D+: 38
F: 266


In [33]:
#top 10 students
ranks = np.argsort(total_marks)[::-1]

print("Top 10 Students:")
for i in range(10):
    student = ranks[i] + 1
    marks = total_marks[ranks[i]]

    print(f"Rank {i+1}: Student {student} - {marks} marks")

Top 10 Students:
Rank 1: Student 111 - 444 marks
Rank 2: Student 272 - 439 marks
Rank 3: Student 108 - 435 marks
Rank 4: Student 400 - 411 marks
Rank 5: Student 174 - 410 marks
Rank 6: Student 83 - 392 marks
Rank 7: Student 394 - 392 marks
Rank 8: Student 466 - 390 marks
Rank 9: Student 181 - 380 marks
Rank 10: Student 374 - 379 marks
